### ISSUE TITLE
README.txt should be README.md

### ISSUE THREAD

**Issue by mstashev** [arkadianriver/spectral#8]
Otherwise your formatting won't show up. 😄

**Comment by arkadianriver** [comment]
Nope, formatting is showing up... _ASCII formatting_, that is. :laughing:

No, seriously, I wanted to keep the same `README.txt` file as in on the originator's http://html5up.net/spectral since this is just a jekyll port of his. Same with the `LICENSE.txt` file. I had to add that little header, though, to try to make it clear this is a port.
